language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - tip
matrix:
    allow_failures:
        - go: tip
install:
    - go get github.com/stretchr/testify/assert
    - go get -d ./... && go test -i ./... && go build -v ./...
